interface MenuItem {
  name: string;
  price: string;
}

interface MenuData {
  [key: string]: MenuItem[];
}

export const menuData: MenuData = {
  "SMOOTHIE": [
    { name: "Oreo Colada", price: "₹180" },
    { name: "Kit Kat Colada", price: "₹200" },
    { name: "Sitafal Colada", price: "₹200" },
    { name: "MANGO COLADA", price: "₹140" },
    { name: "Strawberry Colada", price: "₹140" },
    { name: "CHICKOO COLADA", price: "₹140" },
    { name: "CHOCOLATE COLADA", price: "₹140" },
    { name: "PINEAPPLE COLADA", price: "₹140" },
    { name: "ORANGE COLADA", price: "₹140" },
    { name: "BLACK CURRENT COLADA", price: "₹140" },
    { name: "APPLE COLADA", price: "₹140" },
    { name: "ROSE COLADA", price: "₹140" },
    { name: "LITCHI COLADA", price: "₹140" },
    { name: "Coconut Colada", price: "₹180" },
    { name: "Avacado Colada", price: "₹220" },
    { name: "Kaju Anjeer Colada", price: "₹220" },
    { name: "Blueberry Colada", price: "₹200" },
    { name: "Biscuit Smoothies", price: "₹160" },
  ],
  "MILK SHAKE": [
    { name: "Chikko + Apple M.S", price: "₹90" },
    { name: "Kaju+Badam M.S", price: "₹170" },
    { name: "COLD COCO M.S", price: "₹70" },
    { name: "VANILLA M.S", price: "₹70" },
    { name: "PINEAPPLE M.S", price: "₹70" },
    { name: "ROSE M.S", price: "₹70" },
    { name: "Butter Scotch M.s", price: "₹80" },
    { name: "COLD COFFEE M.S", price: "₹70" },
    { name: "Banana M.s", price: "₹80" },
    { name: "STRAWBERRY M.S", price: "₹80" },
    { name: "CHICKOO M.S", price: "₹80" },
    { name: "Chocolate M.s", price: "₹80" },
    { name: "KESAR M.S", price: "₹90" },
    { name: "MANGO M.S", price: "₹100" },
    { name: "APPLE M.S", price: "₹90" },
    { name: "LITCHI M.S", price: "₹90" },
    { name: "TROPICAL COFFEE M.S", price: "₹90" },
    { name: "FRESH KIWI M.S", price: "₹80" },
    { name: "SP. ORANGE M.S", price: "₹80" },
    { name: "PAPITA M.S", price: "₹90" },
    { name: "MIX FRUIT M.S", price: "₹100" },
    { name: "CHICKOO CHOCOLATE M.S", price: "₹90" },
    { name: "BLACK CURRENT M.S", price: "₹80" },
    { name: "ROSE APPLE M.S", price: "₹90" },
    { name: "CHICKOO+KESAR M.S", price: "₹90" },
    { name: "OREO M.S", price: "₹100" },
    { name: "KHAJUR M.S", price: "₹100" },
    { name: "KHAJUR+CHICKOO M.S", price: "₹100" },
    { name: "KITKAT M.S", price: "₹120" },
    { name: "SP. SITAFAL M.S", price: "₹120" },
    { name: "KAJU M.S", price: "₹170" },
    { name: "BADAM M.S", price: "₹170" },
    { name: "SP. DRY FRUIT M.S", price: "₹180" },
    { name: "SP. KAJU MANGO M.S", price: "₹180" },
    { name: "KAJU ANJEER M.S", price: "₹170" },
    { name: "ANJEER M.S", price: "₹170" },
    { name: "KAJU GULKAND M.S", price: "₹170" },
    { name: "KAJU ROSE M.S", price: "₹170" },
    { name: "KAJU KESAR M.S", price: "₹170" },
    { name: "PISTA M.S", price: "₹200" },
    { name: "SP. AVOCADO M.S", price: "₹200" },
    { name: "CHOCOLATE BANANA M.S", price: "₹90" },
    { name: "GULKAND M.S", price: "₹90" },
    { name: "CHICKOO+BANANA M.S", price: "₹90" },
    { name: "AVOCADO+MANGO M.S", price: "₹200" },
    { name: "FRESH BLUEBERRY M.S", price: "₹180" },
    { name: "BLUEBERRY+STRAWBERRY M.S", price: "₹200" },
    { name: "FRESH RASPBERRY M.S", price: "₹180" },
    { name: "FRESH CRANBERRY M.S", price: "₹180" },
    { name: "FRESH MIX BERRIES M.S", price: "₹200" },
    { name: "BOURNVITA M.S", price: "₹80" },
    { name: "HAZELNUT M.S", price: "₹120" },
    { name: "SP.THANDAI M.S", price: "₹100" },
    { name: "KHAJUR+ANJEER M.S", price: "₹170" },
    { name: "KAJU+KHAJUR M.S", price: "₹170" },
    { name: "ROASTED ALMOND M.S", price: "₹150" },
    { name: "CHICKOO+GULKAND M.S", price: "₹90" },
  ],
  "MILK SHAKE WITH ICE CREAM": [
    { name: "Chickoo + Apple M.S + I.C", price: "₹100" },
    { name: "Kaju + Badam M.S + I.C", price: "₹190" },
    { name: "PINEAPPLE M.S+I.C", price: "₹90" },
    { name: "ROSE M.S+I.C", price: "₹80" },
    { name: "Butter Scotch M.s+i.c", price: "₹100" },
    { name: "COLD COFFEE M.S+I.C", price: "₹90" },
    { name: "Banana M.s+i.c", price: "₹100" },
    { name: "VANILLA M.S+I.C", price: "₹80" },
    { name: "Starwberry M.s+i.c", price: "₹100" },
    { name: "Cold Coco M.s+i.c", price: "₹90" },
    { name: "KESAR M.S+I.C", price: "₹100" },
    { name: "APPLE M.S+I.C", price: "₹100" },
    { name: "ROSE APPLE M.S+I.C", price: "₹100" },
    { name: "Litchi M.s+i.c", price: "₹100" },
    { name: "Fresh Kiwi M.s+i.c", price: "₹100" },
    { name: "SP. ORANGE M.S+I.C", price: "₹100" },
    { name: "PAPITA M.S+I.C", price: "₹100" },
    { name: "MANGO M.S+I.C", price: "₹110" },
    { name: "MIX FRUIT M.S+I.C", price: "₹110" },
    { name: "CHICKOO CHOCOLATE M.S+I.C", price: "₹100" },
    { name: "CHOCOLATE+BANANA M.S+I.C", price: "₹100" },
    { name: "CHICKOO M.S+I.C", price: "₹100" },
    { name: "TROPICAL COFFEE M.S+I.C", price: "₹100" },
    { name: "Blackcurrent M.s+i.c", price: "₹100" },
    { name: "Chocolate M.s+i.c", price: "₹100" },
    { name: "CHICKOO+KESAR M.S+I.C", price: "₹100" },
    { name: "KHAJUR+CHICKOO M.S+I.C", price: "₹120" },
    { name: "OREO M.S+I.C", price: "₹120" },
    { name: "GULKAND M.S+I.C", price: "₹110" },
    { name: "KHAJUR M.S+I.C", price: "₹120" },
    { name: "KITKAT M.S+I.C", price: "₹140" },
    { name: "SP. SITAFAL M.S+I.C", price: "₹140" },
    { name: "KAJU M.S+I.C", price: "₹190" },
    { name: "BADAM M.S+I.C", price: "₹190" },
    { name: "SP. DRY FRUIT M.S+I.C", price: "₹200" },
    { name: "SP. KAJU MANGO M.S+I.C", price: "₹200" },
    { name: "KAJU ANJEER M.S+I.C", price: "₹190" },
    { name: "ANJEER M.S+I.C", price: "₹190" },
    { name: "KAJU GULKAND M.S+I.C", price: "₹190" },
    { name: "KAJU ROSE M.S+I.C", price: "₹190" },
    { name: "KAJU KESAR M.S+I.C", price: "₹190" },
    { name: "PISTA M.S+I.C", price: "₹210" },
    { name: "AVOCADO M.S+I.C", price: "₹220" },
    { name: "CHIKOO+BANANA M.S+I.C", price: "₹100" },
    { name: "AVOCADO+MANGO M.S+I.C", price: "₹200" },
    { name: "FRESH BLUEBERRY M.S+I.C", price: "₹200" },
    { name: "BLUEBERY+STRAWBERRY M.S+I.C", price: "₹220" },
    { name: "FRESH RASPBERRY M.S+I.C", price: "₹200" },
    { name: "FRESH CRANBERRY M.S+I.C", price: "₹200" },
    { name: "FRESH MIX BERRIESM.S+I.C", price: "₹220" },
    { name: "BOURNVITA M.S+I.C", price: "₹100" },
    { name: "HAZELNUT M.S+I.C", price: "₹140" },
    { name: "SP.THANDAI M.S+I.C", price: "₹120" },
    { name: "KHAJUR+ANJEER M.S+I.C", price: "₹190" },
    { name: "KAJU+KHAJUR M.S+I.C", price: "₹190" },
    { name: "ROSTED ALMOND M.S+I.C", price: "₹170" },
    { name: "CHICKOO+GULKAND M.S+I.C", price: "₹110" },
  ],
  "FRESH JUICE": [
    { name: "PINEAPPLE+PLUM JUICE", price: "₹100" },
    { name: "POMEGRANATE+DRAGON JUICE", price: "₹110" },
    { name: "SP.DENGUE JUICE", price: "₹110" },
    { name: "LEMON+GINGER JUICE", price: "₹50" },
    { name: "KOKUM JUICE", price: "₹60" },
    { name: "GREEN+BLACK GRAPES JUICE", price: "₹100" },
    { name: "PEACH+PLUM JUICE", price: "₹100" },
    { name: "WATERMELON+MINT JUICE", price: "₹80" },
    { name: "LEMON JUICE", price: "₹30" },
    { name: "PINEAPPLE JUICE", price: "₹60" },
    { name: "WATERMELON JUICE", price: "₹60" },
    { name: "GUAVA JUICE", price: "₹60" },
    { name: "PAPITA JUICE", price: "₹60" },
    { name: "APPLE JUICE", price: "₹70" },
    { name: "MOSAMBI JUICE", price: "₹60" },
    { name: "ORANGE JUICE", price: "₹60" },
    { name: "PINEAPPLE+MOSAMBI JUICE", price: "₹70" },
    { name: "PINEAPPLE+ORANGE JUICE", price: "₹70" },
    { name: "GANGA JAMUNA SARASWATI JUICE", price: "₹70" },
    { name: "GANGA JAMUNA JUICE", price: "₹70" },
    { name: "MANGO JUICE", price: "₹90" },
    { name: "MUSK MELON JUICE", price: "₹80" },
    { name: "MIX FRUIT JUICE", price: "₹90" },
    { name: "ROSE+WATERMELON JUICE", price: "₹70" },
    { name: "APPLE+PINEAPPLE JUICE", price: "₹80" },
    { name: "WATEMELON+PINEAPPLE JUICE", price: "₹70" },
    { name: "PINEAPPLE+PAPITA JUICE", price: "₹80" },
    { name: "FRESH STRAWBERRY JUICE", price: "₹100" },
    { name: "MARAMMARI JUICE", price: "₹100" },
    { name: "GREEN GRAPES JUICE (S)", price: "₹100" },
    { name: "PEACH JUICE", price: "₹100" },
    { name: "PEARS JUICE", price: "₹90" },
    { name: "POMEGRANATE JUICE", price: "₹100" },
    { name: "Jamun Juice", price: "₹100" },
    { name: "POMEGRANATE+PINEAPPLE JUICE", price: "₹100" },
    { name: "POMEGRANATE+ORANGE JUICE", price: "₹100" },
    { name: "POMEGRANATE+MOSAMBI JUICE", price: "₹100" },
    { name: "FRESH KIWI JUICE", price: "₹100" },
    { name: "STARWBERRY+KIWI JUICE", price: "₹100" },
    { name: "BLACK GRAPES JUICE", price: "₹100" },
    { name: "COCKTAIL JUICE", price: "₹100" },
    { name: "GRAPES+POMEGRANATE JUICE", price: "₹100" },
    { name: "KIWI+PINEAPPLE JUICE", price: "₹100" },
    { name: "FALSA JUICE (S)", price: "₹100" },
    { name: "PLUM JUICE (S)", price: "₹100" },
    { name: "LICHI JUICE (S)", price: "₹100" },
    { name: "RASPBERRY JUICE", price: "₹160" },
    { name: "BLUEBERRY JUICE", price: "₹150" },
    { name: "CHERRY JUICE", price: "₹100" },
    { name: "KIWI+MANGO JUICE", price: "₹100" },
    { name: "KIWI+APPLE JUICE", price: "₹100" },
    { name: "GRAPES+PINEAPPLE JUICE", price: "₹100" },
    { name: "DRAGON JUICE", price: "₹110" },
    { name: "KIWI+DRAGON JUICE", price: "₹110" },
    { name: "PINEAPPLE+DRAGON JUICE", price: "₹110" },
    { name: "AVOCADO JUICE", price: "₹160" },
    { name: "MULBERRY JUICE", price: "₹100" },
    { name: "TRIVENI JUICE", price: "₹110" },
    { name: "KIWI+POMEGRANATE JUICE", price: "₹100" },
    { name: "LEMON+MINT JUICE", price: "₹50" },
    { name: "STRAWBERRY+PINEAPPLE JUICE", price: "₹100" },
    { name: "PASSION FRUIT JUICE", price: "₹100" },
    { name: "FRESH CRANBERRY JUICE", price: "₹150" },
    { name: "FRESH MIX BERRIES JUICE", price: "₹160" },
    { name: "PINEAPPLE+GINGER JUICE", price: "₹70" },
    { name: "SOARCHEERY JUICE", price: "₹150" },
    { name: "RED CURRENT JUICE", price: "₹150" },
    { name: "BLACK CURRENT JUICE", price: "₹150" },
    { name: "BLACKBERRY JUICE", price: "₹150" },
    { name: "Strawberry.apple. Juice", price: "₹100" },
    { name: "Plum Peach Mix", price: "₹100" },
    { name: "1/2 ( Extra Charge )", price: "₹10" },
    { name: "2 With Out Ice And Sugar", price: "₹10" },
    { name: "3 Parcel Charge", price: "₹10" },
  ],
  "FALOODA": [
    { name: "Royal Falooda", price: "₹90" },
    { name: "Butter Scotch Falooda", price: "₹90" },
    { name: "Rose Falooda", price: "₹90" },
    { name: "Strawberry Falooda", price: "₹90" },
    { name: "RAJWADI FALOODA", price: "₹90" },
    { name: "Chocolate Falooda", price: "₹90" },
    { name: "RABDI FALOODA", price: "₹90" },
    { name: "KESAR FALOODA", price: "₹90" },
  ],
  "FALOODA WITH ICE CREAM": [
    { name: "BUTTER SCOTCH FALOODA+I.C", price: "₹100" },
    { name: "AMERICAN FALOODA+I.C", price: "₹100" },
    { name: "RAJBHOG FALOODA+I.C", price: "₹110" },
    { name: "CHOCOLATE FALOODA+I.C", price: "₹100" },
    { name: "KAJU DRAKSH FALOODA+I.C", price: "₹100" },
    { name: "KESAR FALOODA+I.C", price: "₹100" },
    { name: "RABDI FALOODA+I.C", price: "₹110" },
  ],
  "ICE CREAM": [
    { name: "Vanilla I.c", price: "₹30" },
    { name: "Strawberry I.c", price: "₹40" },
    { name: "Pineapple I.c", price: "₹50" },
    { name: "KAJU DRAKSH I.C", price: "₹45" },
    { name: "CHOCOLATE CHIPS I.C", price: "₹45" },
    { name: "KAJU ANJEER I.C", price: "₹50" },
    { name: "RAJ BHOG I.C", price: "₹50" },
    { name: "GREEN PISTA I.C", price: "₹45" },
    { name: "Butter Scotch I.c", price: "₹45" },
    { name: "Black Current I.c", price: "₹45" },
    { name: "AMERICAN DRY FRUIT I.C", price: "₹45" },
    { name: "Golden Pearl I.c", price: "₹45" },
    { name: "SITAFAL (S) I.C", price: "₹50" },
    { name: "MAWA I.C", price: "₹50" },
    { name: "BLUE DIAMOND I.C", price: "₹50" },
    { name: "MANGO (S) I.C", price: "₹45" },
    { name: "COCONUT I.C", price: "₹50" },
    { name: "Fresh Fruit I.c", price: "₹90" },
    { name: "COOKIES CREAM I.C", price: "₹50" },
    { name: "FRESH JAMUN (S) I.C", price: "₹50" },
    { name: "GUAVA (S) I.C", price: "₹50" },
  ],
  "LASSI": [
    { name: "SWEET LASSI", price: "₹40" },
    { name: "ROSE LASSI", price: "₹60" },
    { name: "PINEAPPLE LASSI", price: "₹70" },
    { name: "Strawberry Lassi", price: "₹70" },
    { name: "ZING THING LASSI", price: "₹80" },
    { name: "CHOCOLATE LASSI", price: "₹80" },
    { name: "SP. KESAR LASSI", price: "₹80" },
    { name: "KAJU MANGO LASSI", price: "₹80" },
    { name: "GRAPE FRUIT LASSI", price: "₹80" },
    { name: "FRESH FRUITS LASSI", price: "₹90" },
    { name: "KAJU CREAM LASSI", price: "₹90" },
    { name: "R.RAJESHWARI DRY FRUIT LASSI", price: "₹100" },
    { name: "RAJ BHOG LASSI", price: "₹100" },
    { name: "AMERICAN DRY FRUIT LASSI", price: "₹100" },
  ],
  "SPECIAL VARIETY BLOSSOM": [
    { name: "CHOCOLATE BLOSSOM", price: "₹100" },
    { name: "ORANGE BLOSSOM", price: "₹100" },
    { name: "LITCHI BLOSSOM", price: "₹100" },
    { name: "PINEAPPLE BLOSSOM", price: "₹100" },
    { name: "STRAWBERRY BLOSSOM", price: "₹100" },
    { name: "ROSE BLOSSOM", price: "₹100" },
    { name: "APPLE BLOSSOM", price: "₹100" },
    { name: "BLACK CURRENT BLOSSOM", price: "₹80" },
  ],
  "SPECIAL SUNDAY ICE CREAM": [
    { name: "Fruit Delight", price: "₹170" },
    { name: "Sweet Temptation", price: "₹160" },
    { name: "Banana Split", price: "₹160" },
    { name: "Fruit Salad+ice Cream", price: "₹160" },
    { name: "Love Bite", price: "₹160" },
    { name: "FASHION DELIGHT", price: "₹170" },
    { name: "HOT CHOCOLATE FUDGE", price: "₹170" },
  ],
  "HEALTHY VEGETABLE JUICE": [
    { name: "Mix Vegetable Juice", price: "₹80" },
    { name: "Carrot+beet Juice", price: "₹80" },
    { name: "Carrot Juice", price: "₹80" },
    { name: "Beet Juice", price: "₹80" },
    { name: "A.b.c Juice", price: "₹80" },
    { name: "Beet+pineapple", price: "₹80" },
    { name: "Beet+pomegranet", price: "₹100" },
  ],
  "FRUIT DISH": [
    { name: "PINEAPPLE FRUIT DISH", price: "₹110" },
    { name: "WATERMELON FRUIT DISH", price: "₹90" },
    { name: "MIX FRUIT DISH", price: "₹110" },
  ],
  "MOCKTAIL": [
    { name: "Mango Mania M.t", price: "₹110" },
    { name: "BLUE OCEAN M.T", price: "₹110" },
    { name: "Bicycle M.t", price: "₹110" },
    { name: "Pink Beauty M.t", price: "₹110" },
    { name: "Pineapple Fridge M.t", price: "₹110" },
    { name: "European M.t", price: "₹110" },
    { name: "Night & Day M.t", price: "₹110" },
    { name: "Daisy Dream M.t", price: "₹110" },
    { name: "VIRGIN MOJITO M.T", price: "₹100" },
    { name: "Green Iceland M.t", price: "₹110" },
    { name: "Sparkling Sunrise M.t", price: "₹110" },
    { name: "Rainbow M.t", price: "₹100" },
  ],
  "THICK SHAKE": [
    { name: "VANNILA T.S", price: "₹110" },
    { name: "KESAR ELAICHI T.S", price: "₹120" },
    { name: "STRAWBERRY T.S", price: "₹120" },
    { name: "PINEAPPLE T.S", price: "₹120" },
    { name: "ROSE T.S", price: "₹120" },
    { name: "BANANA T.S", price: "₹120" },
    { name: "Mango T.s", price: "₹130" },
    { name: "CHOCOLATE T.S", price: "₹130" },
    { name: "BLACK CURRENT T.S", price: "₹120" },
    { name: "LITCHI T.S", price: "₹120" },
    { name: "APPLE T.S", price: "₹120" },
    { name: "ORANGE T.S", price: "₹120" },
    { name: "KIWI T.S", price: "₹120" },
    { name: "BLUEBERRY T.S", price: "₹140" },
    { name: "VERY BERRY T.S", price: "₹140" },
    { name: "COFFEE CHOCOLATE T.S", price: "₹140" },
    { name: "SITAFAL T.S", price: "₹150" },
    { name: "KAJU ANJEER T.S", price: "₹190" },
    { name: "BUTTER SCITCH T.S", price: "₹120" },
    { name: "KITKAT T.S", price: "₹140" },
    { name: "OREO T.S", price: "₹120" },
    { name: "AVOCADO T.S", price: "₹220" },
    { name: "WATER MELON T.S", price: "₹120" },
    { name: "KHUS T.S", price: "₹120" },
    { name: "KIWI+PINEAPPLE T.S", price: "₹130" },
    { name: "LITCHI+PINEAPPLE T.S", price: "₹130" },
    { name: "KIWI+STRAWBERRY T.S", price: "₹130" },
    { name: "KAJU T.S", price: "₹190" },
    { name: "BADAM T.S", price: "₹190" },
    { name: "BOURNVITA T.S", price: "₹120" },
    { name: "HAZELNUT T.S", price: "₹150" },
    { name: "THANDAI T.S", price: "₹120" },
  ],
  "FRESH FRUIT SHORT'S": [
    { name: "JAMUN SHORT'S 4CUP", price: "₹160" },
    { name: "GUAVA SHORT'S 4CUP", price: "₹160" },
    { name: "MANGO SHORT'S 4CUP", price: "₹160" },
    { name: "FALSA SHORT'S 4CUP", price: "₹160" },
    { name: "KIWI SHORT'S 4CUP", price: "₹160" },
    { name: "Jamun Shot ( 1 Cup )", price: "₹40" },
    { name: "Strawberry Shots ( 4 Cup )", price: "₹160" },
    { name: "Strawberry Shot ( 1 Cup )", price: "₹40" },
  ],
  "BEVERAGES": [
    { name: "MINERAL WATER 500ML", price: "₹10" },
    { name: "MINERAL WATER 1LTR", price: "₹20" },
    { name: "MONSTER", price: "₹110" },
    { name: "COOLBERG", price: "₹100" },
    { name: "RED BULL (S)", price: "₹125" },
    { name: "RED BULL BIG", price: "₹165" },
    { name: "PLAIN SODA", price: "₹20" },
  ],
};